#!/usr/bin/env ruby

require 'yaml'

IMAGE = 'andschroeder/local-kafka-cluster'

# default cluster size is 3.
cluster_size = ARGV.empty? ? 3 : ARGV[0].to_i

if `uname`.strip == 'Darwin'
  HOST_IP = `ipconfig getifaddr en0 || ipconfig getifaddr en1`.strip
else
  interface=`route -n | grep '^0.0.0.0'`.split("\n")[0].split(" ")[-1]
  HOST_IP = `ip -4 addr show scope global dev #{interface} | grep inet`.split(" ")[1][0..-4]
end

puts "Host IP used for Kafka Brokers is #{HOST_IP}"

COMPOSE = {
  'version' => '2',
  'networks' => { 'cluster' => { 'driver' => 'bridge' } },
  'services' => {
    'zookeeper' => {
      'image' => IMAGE,
      'command' => 'zookeeper',
      'ports' => [ "2181:2181" ],
      'networks' => [ 'cluster' ],
    }
  }
}

def add_broker(id)
  name = "kafka_#{id}"
  port = 9091 + id
  COMPOSE['services'][name] = {
    'image' => IMAGE,
    'environment' => {
      'kafka_port' => port,
      'kafka_id' => id,
      'kafka_ip' => HOST_IP
    },
    'hostname' => name,
    'ports' => [ "#{port}:#{port}" ],
    'networks' => [ 'cluster' ],
    'links' => [ "zookeeper:zookeeper" ]
  }
end

(1..cluster_size).each do |i|
  add_broker(i)
end

File.write('docker-compose.yml', COMPOSE.to_yaml)

`docker-compose --project-name local up -d`
